'use client';

import React from 'react';
import { RecommendationDetail } from '../../lib/types';
import { ShieldCheck, UserCheck, AlertTriangle, ArrowUpRight } from 'lucide-react';
import Link from 'next/link';

interface PriorityActionsTableProps {
  recommendations?: RecommendationDetail[];
  isLoading: boolean;
}

export default function PriorityActionsTable({
  recommendations = [],
  isLoading,
}: PriorityActionsTableProps) {
  if (isLoading) {
    return (
      <div className="bg-slate-900/40 backdrop-blur-md border border-slate-800 rounded-xl p-5 h-80 animate-pulse" />
    );
  }

  // Sort and slice top 10 priority recommendations
  const top10 = [...recommendations]
    .sort((a, b) => b.priority_score - a.priority_score)
    .slice(0, 10);

  return (
    <div className="bg-slate-900/40 backdrop-blur-md border border-slate-800 rounded-xl p-5 shadow-lg flex flex-col justify-between h-full">
      <div>
        <div className="flex justify-between items-center mb-4">
          <div className="flex items-center space-x-2">
            <UserCheck className="w-4 h-4 text-cyan-400" />
            <h3 className="text-sm font-bold text-slate-100 uppercase tracking-wider font-mono">
              Top Priority Enforcement Actions
            </h3>
          </div>
          <Link
            href="/recommendations"
            className="text-[10px] font-bold text-cyan-400 hover:text-slate-100 uppercase tracking-wider font-mono flex items-center space-x-1 transition-colors"
          >
            <span>Full Actions Board</span>
            <ArrowUpRight className="w-3.5 h-3.5" />
          </Link>
        </div>
        <p className="text-slate-550 text-[10px] font-mono mb-4">
          Top 10 highest-impact interventions generated by the Smart City Enforcement Engine
        </p>

        {/* Scrollable Table Container */}
        <div className="overflow-x-auto border border-slate-850 rounded-xl max-h-[380px] overflow-y-auto custom-scrollbar">
          <table className="w-full text-left border-collapse font-mono text-[11px]">
            <thead className="bg-slate-950/80 sticky top-0 border-b border-slate-850 z-10 text-[10px] text-slate-500 font-bold uppercase tracking-wider">
              <tr>
                <th className="px-4 py-3">Priority</th>
                <th className="px-4 py-3">Location</th>
                <th className="px-4 py-3">Action Details</th>
                <th className="px-4 py-3 text-center">Officers</th>
                <th className="px-4 py-3 text-right">Est. Reduction</th>
                <th className="px-4 py-3 text-center">Risk Level</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-850/60 bg-slate-900/10">
              {top10.length > 0 ? (
                top10.map((rec) => {
                  const isCritical = rec.priority === 'Critical';
                  const isHigh = rec.priority === 'High';
                  
                  return (
                    <tr
                      key={rec.junction_name}
                      className="hover:bg-slate-950/50 transition-colors"
                    >
                      {/* Priority Rank */}
                      <td className="px-4 py-3 font-bold text-slate-100">
                        #{rec.rank}
                      </td>
                      {/* Location */}
                      <td className="px-4 py-3 font-semibold text-slate-200 truncate max-w-[200px]" title={rec.junction_name}>
                        {rec.junction_name}
                      </td>
                      {/* Action */}
                      <td className="px-4 py-3 text-slate-400 max-w-[300px] truncate" title={rec.reason}>
                        {rec.reason}
                      </td>
                      {/* Officers count */}
                      <td className="px-4 py-3 text-center font-bold text-slate-100">
                        {rec.officers}
                      </td>
                      {/* Est. Reduction */}
                      <td className="px-4 py-3 text-right font-bold text-emerald-400">
                        {rec.expected_violation_reduction}%
                      </td>
                      {/* Risk Level Badge */}
                      <td className="px-4 py-3 text-center">
                        <span
                          className={`inline-block px-2 py-0.5 rounded text-[9px] font-black uppercase border ${
                            isCritical
                              ? 'bg-rose-950/30 text-rose-450 border-rose-800/30'
                              : isHigh
                              ? 'bg-amber-950/30 text-amber-400 border-amber-800/30'
                              : 'bg-emerald-950/30 text-emerald-450 border-emerald-800/30'
                          }`}
                        >
                          {rec.priority}
                        </span>
                      </td>
                    </tr>
                  );
                })
              ) : (
                <tr>
                  <td colSpan={6} className="px-4 py-8 text-center text-slate-550">
                    No active recommendations found.
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
